default_agent: resume_analyzer_agent
agents:
  resume_analyzer_agent:
    name: resume_analyzer_agent
    language: python
    node_version: null
    entrypoint: C:/Users/Administrator/Documents/GitHub/resume-analyzer-agent/resume_analyzer_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::206409480438:role/ResumeAnalyzerAgentCoreRole-agentcore
      execution_role_auto_create: false
      account: '206409480438'
      region: us-east-1
      ecr_repository: 206409480438.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-resume_analyzer_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: resume_analyzer_agent-j2SNsc9Nf9
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:206409480438:runtime/resume_analyzer_agent-j2SNsc9Nf9
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-resume_analyzer_agent-builder
      execution_role: arn:aws:iam::206409480438:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-8809f23b18
      source_bucket: bedrock-agentcore-codebuild-sources-206409480438-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
